CAREERS = {
    "Entertainment & Performance": [],
    "Media & Journalism": [],
    "Fashion & Styling": [],
    "Beauty & Wellness": [],
    "Art & Design": [],
    "Technology & IT": [],
    "Healthcare & Medicine": [],
    "Education & Training": [],
    "Law & Justice": [],
    "Government & Public Service": [],
    "Defense & Security": [],
    "Business & Finance": [],
    "Marketing & Sales": [],
    "Travel & Tourism": [],
    "Food & Hospitality": [],
    "Engineering & Construction": [],
    "Trades & Skilled Work": [],
    "Agriculture & Environment": [],
    "Transport & Logistics": [],
    "Sports & Fitness": [],
    "Science & Research": [],
    "Spiritual & Wellness": [],
    "Home & Personal Services": [],
    "Printing & Publishing": [],
    "Freelance & Gig Economy": []
}